### ISSUE TITLE
react-native upgrade wipes out all gradle, etc. modifications

### ISSUE THREAD

**Issue by ssomnoremac** [couchbaselabs/react-native-couchbase-lite#10]
In my attempt to add local images to the example project, which any offline app must store somehow, I decided to try to run the upgrade command `react-native upgrade` to see if for some reason [static files](https://facebook.github.io/react-native/docs/images.html#static-image-resources) weren't being supported by something. In doing so, all the gradle config mods from the readme got wiped. 

Is there anything we can do to prevent `upgrade` from doing this or is it just react-native evil that we must keep away from?

**Comment by npomfret** [comment]
I've not found a way to 'nicely' upgrade react native yet.  The best approach I've found is to first (obviously) make sure everything is checked in before you upgrade.  

After running the upgrade, use `rpm link` to get your project files back into shape, and then manually in Xcode add the couchbase framework files back in (from Project Navigator, File > Add Files to ...).

Use a decent IDE that will show you the changes to each file after the upgrade process has finished (I use IntelliJ for this).  Go through each file, check each change thats been made.  If anything has been removed by mistake just revert those lines. I've found that any manual changes I've had to make always get wiped.
