### ISSUE TITLE
external auth session cookie with ^0.6.0

### ISSUE THREAD

**Issue by danlannz** [couchbaselabs/react-native-couchbase-lite#116]
I'm currently using a WebAPI to authenticate users and create a SyncGateway session. How can I use this session cookie with the new Swagger API?

I assume it's only the `manager.server.post_replicate` function that needs to use the session cookie but I can't seem to make it work using the following options
```javascript
        {
          body: {
            source: {
              url: config.SYNC_URL,
              headers: { Cookie: user.session },
            },
            target: dbName,
            continuous: true
          }
        }
```

can anyone show me where I'm going wrong

**Comment by jamesnocentini** [comment]
Is it not working on Android and iOS or just one of them?

**Comment by jamesnocentini** [comment]
I just tested iOS and it works with the following:

```javascript
manager.server.post_replicate({body: {source: {url: 'http://localhost:4984/todo', headers: {Cookie: 'SyncGatewaySession=5018d818fc8f13b4f11b777ead52f464b0ddb12a; Path=/todo; Expires=Thu, 02 Feb 2017 14:49:31 GMT'}}, target: 'todo', continuous: true}})
      .then(res => {
        console.log(res.obj);
      });
```

Session creation from Terminal:

```bash
curl -vX POST 'http://localhost:4984/todo/_session' -H 'Content-Type: application/json' -d '{"name": "user1", "password": "pass"}'

< HTTP/1.1 200 OK
< Content-Length: 114
< Content-Type: application/json
< Server: Couchbase Sync Gateway/1.3.0
< Set-Cookie: SyncGatewaySession=5018d818fc8f13b4f11b777ead52f464b0ddb12a; Path=/todo; Expires=Thu, 02 Feb 2017 14:49:31 GMT
< Date: Wed, 01 Feb 2017 14:49:31 GMT
<
* Connection #0 to host localhost left intact
{"authentication_handlers":["default","cookie"],"ok":true,"userCtx":{"channels":{"!":1,"user1":3},"name":"user1"}}
```

200 OK `:4984/todo/_changes` in HTTPScoop:

<img width="882" alt="_replicate_session" src="https://cloud.githubusercontent.com/assets/2589337/22511771/9c6f1304-e88e-11e6-93cd-fb23fc25bd1a.png" width="25%">

Created a docs ticket to improve the description in the docs.

**Comment by danlannz** [comment]
cheers @jamiltz, it turns out I was missing the database name from the replicate URL param. docs improvement would be great
