### ISSUE TITLE
Getting started - compile problem

### ISSUE THREAD

**Issue by npomfret** [couchbaselabs/react-native-couchbase-lite#12]
After dragging the libraries and frameworks into my Xcode project I'm getting a compile error:

_ReactCBLite.m:15:9: 'CBLRegisterJSViewCompiler.h' file not found_

However, as you can see from the screen shot, the file is there.  I'm quite stuck on this - any ideas?

![screen shot 2016-01-20 at 12 18 30](https://cloud.githubusercontent.com/assets/5489469/12448764/32bac964-bf70-11e5-92c5-781a827d7161.png)

**Comment by jamesnocentini** [comment]
Can you check that libCBLJSViewCompiler.a is indeed in the "Link Binary With Libraries" section of the Build Phases like below:

<img width="1263" alt="pasted_image_21_01_2016__15_06" src="https://cloud.githubusercontent.com/assets/2589337/12478816/9f7bec32-c050-11e5-9aa2-765f86457ada.png">

I think I forgot to add this step in the README. Let me know if that fixes your issue.

**Comment by npomfret** [comment]
Thanks for this, and sorry for the slow reply.  I kept trying over and over and eventually it worked.  I think the problem, but am not sure, is in what is configured in the dialog that pops up when you import the libs.  Could you add a screen shot that describes the correct settings?

**Comment by jamesnocentini** [comment]
Looks like with CBL 1.2, we don't need to import libCBLJSViewCompiler.a and CBLRegisterJSViewCompiler.h anymore. Simplifies the installation steps as well!
