### ISSUE TITLE
monitoring replications

### ISSUE THREAD

**Issue by npomfret** [couchbaselabs/react-native-couchbase-lite#121]
@jamiltz Hey - have you any idea how to monitor replications?  I've asked a questions [here](https://forums.couchbase.com/t/monitoring-replication-ios/12505/5) but my lack of objective-c skills is limiting me!

The code is in my fork [here](https://github.com/npomfret/react-native-couchbase-lite/blob/master/ios/ReactCBLite.m#L247), I'm just trying to attach an observer and have that notify my RN app.  I'm not using the REST api to create the continuous replications (because it can't be controlled as I'd like) so I'm doing it in objective-c.

**Comment by npomfret** [comment]
Got it working.  Needed some threading magic, basally [this](https://github.com/npomfret/react-native-couchbase-lite/blob/master/ios/ReactCBLite.m#L23) did the trick.

It ensures that all CBL method calls are done on the main loop. And for what ever reason that enables the replication change events to bubble through.  So now I can see them inside my JS code.

I'll get all this into master at some point soon.

Also, I've switched everything over the use promises which feels much better.

**Comment by jamesnocentini** [comment]
Glad to hear it works for you! Yes promises are a good fit in this case. It looks like your fork is still using the hand written version of the REST API client rather than the swagger generated one. Did you give the swagger generated client a go? And if so is there anything in it that's blocking you or that you are unsure about?

**Comment by npomfret** [comment]
I've not tired the new one yet.  Just been a bit busy, no other reason not to try it yet.

**Comment by jamesnocentini** [comment]
OK.
