### ISSUE TITLE
CouchbaseLite/CouchbaseLite.h not found

### ISSUE THREAD

**Issue by girvo** [couchbaselabs/react-native-couchbase-lite#14]
I followed the XCode instructions in the README, but no matter what I try I get a build error saying that `'CouchbaseLite/CouchbaseLite.h' file not found`

I've added the Couchbase frameworks to the project and I've added all of the dependencies specified in the README, but for whatever reason the build fails on ReactCBLite.

https://i.imgur.com/fqd8xnX.png

Any ideas?

**Comment by jamesnocentini** [comment]
Hey @girvo 
I'm not sure what's going on here. The steps are not straightforward I know.
Here's a starter project that should compile and run (http://cl.ly/0n0m182b400U). Unzip and run `npm install` as the node modules were to large in size to compress.

**Comment by girvo** [comment]
Awesome, I'll give that a shot today

**Comment by girvo** [comment]
@jamiltz Okay so it compiled this time! However using this example code I'm having a bit of an issue:

``` js
import {manager, ReactCBLite} from 'react-native-couchbase-lite';

ReactCBLite.init(5984, 'admin', 'password');

// Instatiate a new database
var db = new manager('http://admin:password@127.0.0.1:5984', 'kidsoft-guardian');
db.createDatabase()
.then((res) => {
    alert('Done!');
})
.catch(err => { alert(err.message); });
```

It alerts with `Network request failed`, and checking the simulators logs:

```
Jan 28 12:27:41 Joshs-MacBook-Pro NewProject[97931]: Launching Couchbase Lite...
Jan 28 12:27:41 Joshs-MacBook-Pro NewProject[97931]: Couchbase Lite url = (null)
Jan 28 12:27:41 Joshs-MacBook-Pro NewProject[97931]: Running application "NewProject" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```

I also get the same error if I swap `127.0.0.1` with `localhost`

**Comment by DaveAdams88** [comment]
Hey @girvo and @jamiltz, i'm also getting this error, any of you guys figure it out?

**Comment by jamesnocentini** [comment]
Tried with react native 0.23 and it worked fine on my machine. Maybe it was specific to an earlier version of react native. Please reopen if you still encounter the issue.
