### ISSUE TITLE
Couchbase Lite 2.0 compatibility

### ISSUE THREAD

**Issue by rghorbani** [couchbaselabs/react-native-couchbase-lite#145]
When will you implement the libraries compatibility for couchbase lite 2.0?
@jamiltz @npomfret

**Comment by npomfret** [comment]
I'm afraid I gave up with couchbase lite. I just couldn't get it to work reliably, and the dev team weren't;t keen on fixing the bugs I raised.

**Comment by ugendrang** [comment]
+1

**Comment by ugendrang** [comment]
It looks support for cross-platform JS is being evaluated for post Couchbase Mobile 2.0 release. 
@jamiltz @npomfret , can you please let us know when the cross-platform JS couchbase mobile will be released?

**Comment by jamesnocentini** [comment]
There are no plans to release a cross platform version for 2.0 at the moment. But you can build your own wrapper around the 2.0 native API with the native modules functionality in React Native.
