### ISSUE TITLE
Please help with install instructions

### ISSUE THREAD

**Issue by TomClarkson** [couchbaselabs/react-native-couchbase-lite#15]
I am new to react native and I can't follow through the installation.

Would you please be able to record a video of installing couchbase-lite on ios?

For example I am up to dragging Couchbase Lite .framework's but I can't see a frameworks folder.

![image](https://cloud.githubusercontent.com/assets/2054503/12897808/7e04767e-cf0e-11e5-85dd-1f73456acf86.png)
I'm not sure how you get to this folder state when this is what I have below.

![screen shot 2016-02-09 at 9 16 38 am](https://cloud.githubusercontent.com/assets/2054503/12897713/e47579f4-cf0d-11e5-8c20-2b369c8aaa50.png)

Also I see a ios (Cocoapods) guide, is this a mutually exclusive way to install? It looks a bit easier.

Many thanks,
Tom

**Comment by adamski** [comment]
The Cocoapods method is only if you have installed React Native with Cocoapods. If you've installed RN the more common way (via `react-native init`) then I don't think its good to mix the two methods.
