### ISSUE TITLE
Querying views

### ISSUE THREAD

**Issue by npomfret** [couchbaselabs/react-native-couchbase-lite#17]
I'm having an issue querying a view that as a compound key (of 2 items).  The url I am constructing is returning the entire view, but what I want is a subset of that view.  From the [docs](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/couchbase-lite/native-api/query/index.html) I understand that I need to specify a _startKey_ and _endKey_ as url parameters.  

The _startKey_ should be an array of 1 item. Correct?

The _endKey_ should be an array of 2 items, the 1st being the same as my _startKey_ and the 2nd being an empty object _{}_. Correct?

So I now have json arrays in my url as parameters.  Should they be url encoded?  It doesn't seem to matter if I do or don't, I still get the full view back.  Is a _GET_ the wrong method?

I guess my question is, **how do I construct an http request to query a view with a compound key**?

Finally, (and I think maybe unrelated) I notice form the source code on [index.js](https://github.com/fraserxu/react-native-couchbase-lite/blob/master/index.js) _makeRequest_ function that the 3rd argument is called _params_ which gets passed to the _fetch_ (as _settings.params_).  I can't see anything in the fetch docs called params??  Is this params object supposed to be url parameters?  I which case I think the _makeRequest_ function needs to be altered, maybe something like this:

```
makeRequest: function(method, url, params, data) {
    var queryString = "";

    if(params) {
      var bits = [];

      for(var key in params) {
        var value = options[key];
        var jsonValue = JSON.stringify(value);
        var part = key + "=" + encodeURIComponent(jsonValue);
        bits.push(part);
      }

      queryString = "?" + bits.join("&");
    }

    var fullUrl = url + queryString;

    var settings = {
      method: method,
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'Authorization': this.authHeader
      }
    };

    if (data) {
      settings.body = JSON.stringify(data);
    }
    return fetch(fullUrl, settings).then((res) => {
      if (res.status == 401) {
        console.log(res);
      }
      return res.json();
    }).catch((err) => { throw err; });
  }

```

**Comment by jamesnocentini** [comment]
Hey @npomfret, Good question! I'd suggest to ask this on the couchbase forums https://forums.couchbase.com/. Once you have the URL figured out we can change the plugin accordingly if necessary.

**Comment by npomfret** [comment]
Ok, I've got it working.  It looks like the current implementation of fetch isn't quite right and the 3rd argument params is indeed supposed to be the query string parameters.  Here's my current work-around.  It's a _queryView_ function that delegates to the existing one, but crucially does not pass in that 3rd parameter.  That 3rd param seemed to break the IOS http stack somehow even if I passed in an empty object _{}_ and a url with query string parameters correctly added to it.

```
LocalDatabase.prototype.queryView = function(designDocumentName, viewName, options) {
  var url = this.localDatabaseUrl + "/" + localDbAppName + "/" + designDocumentName + "/_view/" + viewName;

  var queryString = "";

  if(options) {
    var bits = [];

    for(var key in options) {
      var value = options[key];
      var jsonValue = JSON.stringify(value);
      var part = key + "=" + encodeURIComponent(jsonValue);
      bits.push(part);
    }

    queryString = "?" + bits.join("&");
  }

  var fullUrl = url + queryString;

//  console.log(fullUrl);

  return this.nativeDb.makeRequest("GET", fullUrl);
}

```
