### ISSUE TITLE
Documentation questions

### ISSUE THREAD

**Issue by jimthedev** [couchbaselabs/react-native-couchbase-lite#2]
Hi there,

Thanks for creating this. Couple questions for you from a newbie.

Can you describe what the auth story is in more depth? When does the username and password get transferred over the wire to the sync gateway? I'd assume it is just during the login and then once that happens cblite will cache the cookie and will use it until it expires. What happens at expiration?

In the android instructions I see where I'd put my couchbase URL, but not for iOS. How does ios know what db url I want to use?

Thanks much.

**Comment by fraserxu** [comment]
Hi @jimthedev The documentation for the iOS section is the setup process only, the usage is exactly the same as in Android.

```
import ReactCBLite from 'react-native-couchbase-lite'
// init the database with a port and login credentials
ReactCBLite.init(5984, 'admin', 'password')
```
