### ISSUE TITLE
Cannot replaced a design document

### ISSUE THREAD

**Issue by npomfret** [couchbaselabs/react-native-couchbase-lite#21]
I'm getting a:
`{ status: 409, reason: 'conflict', error: 'conflict' }
`
response when attempting to replace a design document.  According to the [docs](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/design-document/put---db--_design--design-doc-/index.html) PUT should create or updates a design document.  Seems that it only creates.

**Comment by ssomnoremac** [comment]
I'm assuming you're using documentUpdate. You need to pass the documentRevision string as the second argument which you can get from a previous response using `response.rev`

**Comment by npomfret** [comment]
Thanks
