### ISSUE TITLE
How to deal with failed update

### ISSUE THREAD

**Issue by npomfret** [couchbaselabs/react-native-couchbase-lite#22]
Is there a way to detect if or not a document change has failed to reach the server because the sync-gateway rejected it?

I have a client that attempted to make a change it was not authorised to do.  The sync-gateway rejected it as expected, but now that client has a different document revision to everyone else.

**Comment by ssomnoremac** [comment]
```
updateDocument(doc, rev)
  .then((res) => {
    if (res.status == 401) {  // maybe catch other codes as well
      makeItKnownThisDidntWork(res.id)  // whatever you want to do 
    }
  });
```

**Comment by npomfret** [comment]
That's my point, the push from my react-native app to CBLite was successful - I get a response that looks like:

```
{ id: '-Qmgsa9Jw8RpZ7979Emo4TC',
  rev: '2-82bcf259f92e67b099cd1336c5b13418',
  ok: true }

```

And that's the document that is see in my local views.

I can see in the logs, both client and server that the underlying write to the sync-gateway has failed:

```
19:55:46.778‖ WARNING: CBLRestPusher[http://macmini.local:4984/sync_gateway]: _bulk_docs got an error: {
    error = forbidden;
    id = "-Qmgsa9Jw8RpZ7979Emo4TC";
    reason = "wrong user";
    status = 403;
}
```

And on the server:

`Sync fn rejected: ...--> 403 wrong user
`

So how does my RN app know that it's been rejected?  And what should it do then?

Also, it seems that once CBLite is in this state then legitimate changes to that document no longer seem to be coming though.

**Comment by jamesnocentini** [comment]
There's no way for the server to trigger a delete on the client if the sync function rejected the revision. It's just a different way of thinking since the data storage is completely decentralised with Couchbase Mobile. The recommendation is usually to do all the necessary validation on the client side.

**Comment by npomfret** [comment]
Understood, thanks.  So if I manage to get a client into this situation there's no way to determine that it's happened? And no way to recover from it?

Is it actually impossible to stop this from happening?  Imagine a client does all the necessary checks and decides that it's allowed to make a change (by replicating the logic in the sync-gateway maybe?).  Then at the last possible moment the permissions for that client is revoked.  It makes the change assuming that it's allowed to, but it gets rejected by the sync gateway because it was effectively working with out-of-date information.

**Comment by jamesnocentini** [comment]
Correct, validation on the server side only happens once the document is pushed to the Sync Gateway. And validation on the client side can be done in any way before the doc is written to the database.

**Comment by npomfret** [comment]
Thanks, again.  This is concerning.  You're saying that its impossible to stop this from happening, and there's no way to detect its happened and now way to recover from it.

How do people work around this?  Client side checks are simply not able to prevent it, they can merely reduce the chance of it happening.

My observation is that when this happens, the client no longer receives any updates to the document in question.  It's effectively stuck now at the point the change was refused.  No more updates.

**Comment by jamesnocentini** [comment]
You should ask that question on the Couchbase forums. I'm not entirely sure what happens to the replication in that case.

**Comment by jamesnocentini** [comment]
@npomfret I'll close this but can you paste the link to the Couchbase forums post for anyone who might come across this issue.

**Comment by npomfret** [comment]
https://forums.couchbase.com/t/question-about-conflicts/7211/10?u=nick-couchbase
