### ISSUE TITLE
Is it possible to build more code exemple

### ISSUE THREAD

**Issue by juliencousineau** [couchbaselabs/react-native-couchbase-lite#23]
It can be really great if you build more code exemple specific to React Native.

It's really difficult to get started with couchbase, even if I really want the sync offline / online feature, the learning curve when it's your first time, is really hard.. and my time is limited

Mostly if you can get exemple of 
- Replication
- Querying <- I really dont get this part
- Adding document
- Edit document
- Troubleshooting (Sync server with couchbase lite and couchbase server)

I'v been able to connect and make Sync Server communicate with my couchbase server + adding some document in my lite one, but doing the end to end transaction, and querying my online documents after is really not clear.. and I'm pretty sure I'm not the only one here.

And I read a lot.. lot of couchbase documentation. all written in obj-c or java

Thank you!
J

**Comment by jamesnocentini** [comment]
Thanks for the feedback, yes there’s lots of things that could be done.

The good thing is that the same concepts apply on each platform and usually if the Couchbase documentation isn’t enough you can check out the CouchDB documentation because the REST API (which is used here) is CouchDB compatible.

**Comment by juliencousineau** [comment]
If I get right your answer are you telling that a lot of things need to be implemented (wrapped around the API) or its already there, but still not well documented?

Like I see : 

createDesignDocument and queryView

I'm not sure what they actually do

I'm really interesting in how to use them into my React Native project. can you point me to an code exemple

I will look at the couchDB doc

thank you a lot for the quick response !
Cheers
J

**Comment by jamesnocentini** [comment]
Yes the wrapper code lives in https://github.com/fraserxu/react-native-couchbase-lite/blob/master/index.js but you don’t have to use it.

You can use fetch or any other http library in javascript to query the local server on `http://localhost:5984`. And all the endpoints are well documented in the CouchDB docs.

**Comment by jamesnocentini** [comment]
Closing. Let's create issues with the specific example that you'd like to see.
