### ISSUE TITLE
saving attachments to couchbase using FormData

### ISSUE THREAD

**Issue by ssomnoremac** [couchbaselabs/react-native-couchbase-lite#24]
you can't use fetch to get binary files and then save the res.blob() to couchbase. Binary data isn't passed across the bridge. What you can do is use the [FormData](https://github.com/facebook/react-native/blob/master/Libraries/Network/FormData.js) to post the image passing the url of the image in the body of the FormData. However, it doesn't seem to be working. I seem to remember being able to post FormData to couchbase lite but maybe not?

**Comment by jamesnocentini** [comment]
Sorry for the late reply! Can you post the request code with the FormData that's failing?

**Comment by npomfret** [comment]
Did you figure this out?  I'm struggling to figure out how to send an image using the couchbase lite rest API

**Comment by npomfret** [comment]
I've written a bit of native code to deal with upload binary attachments.  Not added instructions to the docs yet but it would be good if someone else could try it out

https://github.com/couchbaselabs/react-native-couchbase-lite/pull/42

New function is called _saveAttachment_, and to load the data use _getAttachmentUri_ to generate a url.  As discussed the urls don't work for images in android yet.
