### ISSUE TITLE
Spurious 401 responses from CBL

### ISSUE THREAD

**Issue by npomfret** [couchbaselabs/react-native-couchbase-lite#27]
My app receives occasional 401 responses when loading documents via the rest API.  I see this in the logs of my react-native app:

> { _bodyInit: '',
>   _bodyText: '',
>   type: 'default',
>   url: 'http://admin:pass@localhost:5984/datr_20160315t183202246z_user3/2fd6e2791cb315363b23d5ab6d4b5a4b',
>   status: 401,
>   ok: false,
>   statusText: undefined,
>   headers: 
>    { map: 
>       { 'accept-ranges': [ 'bytes' ],
>         'www-authenticate': [ 'Digest realm="CouchbaseLite", qop="auth", nonce="474ED7F2-EF1F-4821-B0D0-61BD6294CA18"' ],
>         'content-length': [ '0' ],
>         date: [ 'Thu, 17 Mar 2016 14:27:04 GMT' ] } } }

The current user definitely has access to the document.  If they didn't why would it be on the device, right?  Subsequent requests for the same document work fine.

**Comment by jamesnocentini** [comment]
@npomfret are you still seeing those errors?

**Comment by npomfret** [comment]
I've changed my app so they aren't happening.  I think the problem happens whens its syncing a lot, like when I first start my app.  Documents get delivered to my device but if you try and load them while the sync process is busy you sometimes get a 401... wait a little while and the 401 disappears. 

So now my app tries to wait for the sync process to finish by monitoring the active tasks.  That seems to have worked around the problem.

**Comment by jamesnocentini** [comment]
OK. Which version of iOS are you running the app on?

**Comment by npomfret** [comment]
9.3

**Comment by npomfret** [comment]
I should clarify - I do still get them during normal running of my app, but they are rare now.  There's some code in the javascript the explicitly checks for a 401 (which I didn't add, I only changed the error messages and behaviour).  So its possible that someone else had the same problem.

**Comment by npomfret** [comment]
I've just noticed I occasionally get them from querying views as well as documents.  Pretty sure this isn't anything to do with this project though.  More likely a bug in CBL is suspect.

https://forums.couchbase.com/t/occasional-401-responses-from-cbl-rest-api/7839

**Comment by jamesnocentini** [comment]
I'm not sure. Other projects are also using the Android listener and it's not causing those 401 unauthorized errors. The auth header gets added here https://github.com/couchbaselabs/react-native-couchbase-lite/blob/master/index.js#L303. It would be useful to run an http tool like Charles or HttpScoop to see if the requests are always sending the auth header.

**Comment by npomfret** [comment]
I added a temporary work around in the javascript code to just retry if a 401 is returned.  Works well so far.

Is it time to do another release?
