### ISSUE TITLE
Atomic Counter

### ISSUE THREAD

**Issue by ssomnoremac** [couchbaselabs/react-native-couchbase-lite#31]
I'm going to write an atomic counter api to increment a document key

/user::234::post::12

but is that something that belongs in this module? And it begs the question: is using a bridge to the REST API over one to the platform specific APIs sustainable for larger projects?

**Comment by jamesnocentini** [comment]
You can definitely build large applications with the REST API. If you find that's it's slow or not responsive as it should be you can always open a ticket in the respective repo on github. The only difference using the REST API compared to native is the webserver (which is in each an open source webserver, TJWS for CBL Android and CocoaHTTPServer for iOS) and the request/response handling code.

**Comment by jamesnocentini** [comment]
I'm curious to know how you're thinking of implementing the atomic counter.

**Comment by ssomnoremac** [comment]
I'm not sure. I assumed I'd create a document `_counter` in each database with a counter and just keep the value there. So I guess it could be `createDatabaseWithCounter` to initiate a database where `createDocument` would automatically increment. I haven't given it too much thought yet tbh.

**Comment by ssomnoremac** [comment]
say I want to do `UserID` + `counterID` like so:

```
u::bob-1457227348::rs::18
  baseID::prefix::counter
```

The idea is to store the counter in the '_counter' doc using the key of the UserID (baseID) to enforce atomic. This is what I have so far: 

```
   incrementAndCreate: function (jsonDocument, baseID, prefix) {
    let counter;
    this.getDocument('_counter')
      .then((res) => {

        // if no counter, create an empty counter
        if (res.status == 404) {
          this.createDocument({}, '_counter')
            .then((response) => {
              counter = response;
            }
        } else { counter = res; }  // existing counter         

        // create or increment the counter field with baseID key
        if (counter[baseID] != undefined){
          counter[baseID]++;
        } else { counter[baseID] = 0; }

        let rev = counter['_rev'];
        delete counter['_rev']
        return this.updateDocument(counter, rev)
      })
      .then((res) => { return this.createDocument(jsonDocument, baseID + "::" + prefix + "::" counter[baseID]) })
      .catch((err) => { throw err; });
  },
```
