### ISSUE TITLE
database.listen() is documented but not implemented

### ISSUE THREAD

**Issue by jp7** [couchbaselabs/react-native-couchbase-lite#32]
The README mentions `void database.listen` which I assume is for listening to `GET /{db}/_changes` 
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/rest-api/database/get-changes/index.html

But it does not seem to be implemented in the manager.
There doesn't seem to be anything else that corresponds to `_changes`

**Comment by martypenner** [comment]
I've been hacking away on a separate experiment that would allow this. It's a big change that requires much more state management in the bridge module than it currently deals with. I've been swiping some code from [the other react-native-couchbase library](https://github.com/Upinion/react-native-couchbase-lite/blob/master/ios/RCTCouchBase/RCTCouchBase/RCTCouchBase.m). Would love to see a merging of the two projects to provide a more complete API.

@fraserxu Is `database.listen` something being worked on currently? I'd hate to be duplicating effort.

**Comment by blairio** [comment]
There has been a couple of commits to expose the _changes endpoint and some other useful endpoints. And they fixed the converting of params to a query string.

It still relies on the REST interface which seems to be the theme of this project.
We have been able to listen to changes using fetch with long poll, and loop ourselves for the next change.

https://github.com/fraserxu/react-native-couchbase-lite/commit/f37fd107a783f273ff409697bd794190398581ab
https://github.com/fraserxu/react-native-couchbase-lite/commit/b57437d91df337b5ef6d15cc5a739edd12faf90e

**Comment by martypenner** [comment]
Do you have an example of a successful long polling implementation? Nothing I've tried has been resilient enough.

The big thing for me is listening to replication progress, especially on a database with many documents. I know of no way to do that with the REST API alone.

**Comment by blairio** [comment]
This is what we have been working on so far:
https://gist.github.com/blairio/dc116c70911553a9e6aaa13a3aee24b5

It is early days for us and still a work in progress and perhaps has not been tested with the more stressful scenarios that you are dealing with. We have yet to figure out how to determine the status of replication and how to control it. 

The gist I posted works in the iOS simulator, but we are having difficulty running couch base lite on a an actual iOS device. After starting the local couch base lite server the call `this.database.createDatabase()`  gets rejected with a 401 not authorized. @martypenner, would you perhaps have experienced this issue yourself?

**Comment by martypenner** [comment]
Interesting. I like that implementation. I think a few of my issues have been stemming from using CouchDB on the server, as opposed to Couchbase's line of products. There seem to be minor, but important inconsistencies in the protocol.

> this.database.createDatabase() gets rejected with a 401 not authorized

I've not encountered that issue before. I assume you're using Couchbase's full suite of products (e.g. Sync Gateway)?

**Comment by blairio** [comment]
The local (client) db is couch base lite, no gateway, and the authentication done locally is basic auth. Accessing the local client through REST with basic auth is what fails on a device but not the simulator.

If we start the local listener without any authentication (ie. we do not call `[listener setPasswords:@{username: password}];`) Then the rest client works on both the device and simulator.

Our remote replication DB is couchbase with sync gateway in front of it. We haven't tried any authentication for the remote yet.

**Comment by martypenner** [comment]
Strange. I've not encountered that at all. Everything is working fine on both actual device and simulator. That's tested with both Couchbase Lite 1.2.0, and the upcoming 1.2.1 release with [these changes](https://github.com/couchbase/couchbase-lite-ios/commit/ffff4226c99b8a5c7da515d1d0bda07d6294119e) cherry-picked.

**Comment by blairio** [comment]
With respect to listening to DB changes Using the additions to master of `latestRevision` and `getChanges` with long polling has been working well for us AFAICT. This issue could probably be closed.

**Comment by martypenner** [comment]
> Using the additions to master of latestRevision and getChanges with long polling has been working well for us AFAICT

That sounds fine to me. Might be good to have an example of this in the docs.

> This issue could probably be closed

Agreed. The use case for listening to replication progress is still not covered, but that discussion can always be had in another issue.

**Comment by jamesnocentini** [comment]
@blairio regarding the 401 unauthorized, this issue seems to be the same scenario https://github.com/couchbaselabs/react-native-couchbase-lite/issues/27. Let's continue the discussion there.

Did anyone try using xmlhttprequest (https://facebook.github.io/react-native/docs/network.html)? I tried with fetch promises but couldn't make the recursive longpoll work.

**Comment by npomfret** [comment]
Instead of using a 'listen' approach I tried polling the _changes_ feed, which so far has worked well.  There's a hint on how to do it [here](https://github.com/couchbaselabs/react-native-couchbase-lite#getchangesoptions).

Basically, I call _getChanges()_, make a note of the last change and use that in the subsequent call.  And wrap the whole thing up in a _setTimeout(..., 50)_ to do it every 50ms.

**Comment by martypenner** [comment]
@npomfret That sounds like a sure way to kill the phone's battery quickly, though I haven't profiled to know for sure. That's one of my motivators for implementing a `listen` approach using a more integrated implementation with couchbase lite.

**Comment by blairio** [comment]
This is the wrapper that we are using right now with long polling  https://gist.github.com/blairio/8d959a22ef089bb7ebc1547a27110931
Seems to be ok so far, but we are still in development so all the data has basically test data.

I also noticed that the socket listener stops when the device is locked, so we now control the listener in the App Delegate: https://gist.github.com/blairio/ea8570f7db4311818692594473c185ca

**Comment by npomfret** [comment]
I agree a proper _listen_ approach would be much better, but polling doesn't seem too bad so far.  I've been keeping and eye on the CPU levels and it seem to sit around 5% on an iPhone which doesn't feel to bad.

**Comment by jamesnocentini** [comment]
@blairio thanks for sharing the wrapper you're using. I'm curious which version of RN allows the call to `require("EventEmitter")`. I've tried with 0.23 but it says the module isn't installed. Did you have to install any additional module?

**Comment by blairio** [comment]
Well, the funny thing is - my first attempt was within a fork of react-native-couchbase-lite where I was trying to import `EventEmitter` within index.js I had the same problem and I could not figure it out. But when I put the wrapper in the codebase of my React Native App then I could import `EventEmitter`.  I have no idea why and I have no idea how the react-native package exposes `EventEmitter`.

**Comment by jamesnocentini** [comment]
Looks like we can use the events module to get the same functionality from within the react native couchbase lite module. The PR is at https://github.com/couchbaselabs/react-native-couchbase-lite/pull/41.

**Comment by yonahforst** [comment]
@jamiltz not sure if I should comment here or open a new issue, but adding `listen()` bumped the CPU usage on my iOS simulator from 3% to 150% 😰

``` js
  this._database.getInfo()
    .then((res) => {
        this._seq = res.update_seq - 1
        this._database.listen({seq: this._seq, feed: 'longpoll'});

        this._database.changesEventEmitter.on('changes', function (e) {
            if (e.last_seq != this._seq) {
                console.log(e)  
                this._seq = e.last_seq
            }
        }.bind(this))
    })
```

**Comment by yonahforst** [comment]
ok, turns out the issue is that the correct param name is `since`, not `seq`: http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/database/get-changes/index.html#story-h2-2

because I wasn't sending a valid sequence filter, the `_changes` endpoint would respond immediately and the poller would issue a new xmlhttprequest request, which also responded immediately. It would just keep calling the `_changes` endpoint over and over again, without waiting for actual changes.

created pull request https://github.com/couchbaselabs/react-native-couchbase-lite/pull/46
