### ISSUE TITLE
LiveQuery support

### ISSUE THREAD

**Issue by yonahforst** [couchbaselabs/react-native-couchbase-lite#40]
Any plans to add livequery support? You probably won't be able to use react-native's new promise resolve/reject but maybe with the older callbacks?

**Comment by jamesnocentini** [comment]
Another way to do this is with filters on the changes feed. Something like `_changes?since=seq&feed=longpoll&filter=ddoc/filtername`.

Prior to that you'll have to register the filter. It works like views except you can't emit and have to write them under the `filter` in the design document:

```
{"filter": "function(doc) { ... return true/false}"}
```

**Comment by yonahforst** [comment]
I'm still learning but will the react-native `fetch` api work with a longpoll feed? My experience with promises is that once resolved, they are discarded.

**Comment by jamesnocentini** [comment]
@yonahforst here's an example of the changes feed with a filter function https://github.com/couchbaselabs/react-native-couchbase-lite/blob/master/ReactNativeCouchbaseLiteExample/index.android.js#L62-L65 combining the listen method with a filter function. This functionality isn't on npm yet.

**Comment by yonahforst** [comment]
thanks @jamiltz!
