### ISSUE TITLE
Don't have method "listen" on latest version 0.2.4

### ISSUE THREAD

**Issue by Gipxy** [couchbaselabs/react-native-couchbase-lite#50]
Steps:
1. npm install react-native-couchbase-lite --save
2. Try to use db.listen, but got no method error

**Comment by npomfret** [comment]
Yes, sorry. It's in [master](https://github.com/couchbaselabs/react-native-couchbase-lite/blob/master/index.js#L298) but hasn't been released yet.  Looks like the docs got updated ahead of the release.

**Comment by Gipxy** [comment]
yeah, for right now, I just copied index.js to project source code, and still work fine, thanks
