### ISSUE TITLE
Documentation Problems

### ISSUE THREAD

**Issue by sambwest** [couchbaselabs/react-native-couchbase-lite#55]
Hi,

I'm new to couchbase so please forgive me if I'm wrong but I think I have come across a few problems in the documentation which took me ages to figure out! 

1) The serialisation (toString) of the "map" method is in the wrong place. You have it on the view object rather than the "map" method.

e.g docs say:

``` javascript
let designDoc = {
  person_age_view: {
    "map": function (doc) {
      if(doc.type === 'person') {
        emit([doc.gender, doc.age], null);
      }
    }
  }.toString()
}
```

Should say: 

``` javascript
let designDoc = {
  person_age_view: {
    "map": function (doc) {
      if(doc.type === 'person') {
        emit([doc.gender, doc.age], null);
      }
    }.toString()
  }
}
```

2) For me to get be able to queryView's I had to define the view by wrapping the document definitions in 'views'.

e.g. docs say:

``` javascript
let designDoc = {
  person_age_view: {
    "map": function (doc) {
      if(doc.type === 'person') {
        emit([doc.gender, doc.age], null);
      }
    }
  }.toString()
}
```

When it should be: 

``` javascript
let designDoc = {
  views: {
    person_age_view: {
      "map": function (doc) {
        if(doc.type === 'person') {
          emit([doc.gender, doc.age], null);
        }
      }.toString()
    }
  }
}
```

**Comment by npomfret** [comment]
Thanks for this, you are absolutely correct.  I'll get them updated.
