### ISSUE TITLE
Calling deleteDatabase() doesn't clear view cache

### ISSUE THREAD

**Issue by sambwest** [couchbaselabs/react-native-couchbase-lite#58]
Hi, 

Calling  deleteDatabase() doesn't seem to clear view cache or remove the data, not sure which. 

1) I clear the database with deleteDatbase()
2) I re-populate the database with new data.
3) I query the view expecting to see the new data and the old data remains.
4) If I clone the existing view with a different name it returns the new data.

Sam

**Comment by npomfret** [comment]
I think this is a bug in the couchbase lite project, rather than the react-native wrapper around it.

**Comment by sambwest** [comment]
OK, I'll open over there.
