### ISSUE TITLE
continuous replication from sync_gateway freezes

### ISSUE THREAD

**Issue by yonahforst** [couchbaselabs/react-native-couchbase-lite#61]
I noticed that sometimes the CBL Pull replication just stops syncing with the sync_gateway. I need to stop and restart the app to get the replication working again (cmd + r doesn't help).

When I look at `http://yonahs-macbook-pro-2.local:5984/_active_tasks` both the pull and push replication have a status of `idle`. When I make changes to a document on the sync_gateway, the changes don't get pulled down to the app.

I've been trying to figure out the steps to reproduce this issue. Here is the closest I've gotten so far: https://github.com/yonahforst/couchbase-react-native-test

1) clone, npm i, and run the app on the iOS simulator. 
2) start a sync_gateway server with a database named `test` (you can use the sync_gateway.json from the repo)
3) open http://localhost:4985/_admin/db/test/documents/1234 in your browser and start hitting the save button. The first save will create the document, subsequent saves will increment the rev number. You should see the rev number incrementing in the simulator too.

Ok, this doesn't reproduce my issue exactly, but I found something similar where the listener stops updating the view at around rev 9 and 99 ( i haven't made it to 999)

**Comment by npomfret** [comment]
I've seen similar issues, only on android though. What os are you using?

**Comment by yonahforst** [comment]
iOS 9.3 on the simulator and 9.3.1 on the iPhone 6.

I'm not able to fully reproduce my issue in the example app. In the example above, hitting cmd+r brings the rev number up to date, whereas in my app I need to stop and restart the app to get the replication syncing again.

Furthermore, in the example app if I go to `http://admin:pass@yonahs-macbook-pro-2.local:5984/test/1234` I see the latest rev number (in sync with the sync_gateway). In my app, in the issue that I'm experiencing, I see the rev number from when my app stopped syncing with sync_gateway. This leads me to believe that these are two separate issues.

**Comment by yonahforst** [comment]
here are my ios logs. https://gist.github.com/yonahforst/3859beefbe1cf404a92b1b6264b186a2
you can see that the last `CBLRestPuller` entry is around line 3191

**Comment by npomfret** [comment]
There is a known bug on IOS that happens when the phone goes to sleep it looses its local connection to CBL.  Is that happening?

If it's not that have you tried looking at the _changes feed coming from the sync gateway to the device?  Be sure to log in to the _changes feed using the same credentials as your app uses.  Does your rev appear in there?

Can you reproduce on Android?

**Comment by yonahforst** [comment]
Hi @npomfret! I don't think that's happening in this case. It happens even when the app doesn't go to sleep, but just sits idle for a minute or two. Also, as I understand it, that bug is caused by iOS closing the socket to the CBLLiteListener, and in this case I'm able to get the document from the simulator via curl. That seems to indicate that the listener port is still open, but just isn't syncing with the sync_gateway.

I had a look at the _changes feed from the sync_gateway, the correct revision number appears there.
Here is a side-by-side look at the `_active_tasks` endpoint on the simulator, the document on the simulator, and the `_changes` feed from the sync_gateway:
![screen shot 2016-06-14 at 12 46 03](https://cloud.githubusercontent.com/assets/1440796/16040137/2a78b92e-322e-11e6-8cb8-e9e668c60223.png)

**Comment by npomfret** [comment]
Have you checked to see if the document is in conflict?

**Comment by npomfret** [comment]
I also think this is probably best asked on the couchbxse-lite-ios git repo.

**Comment by npomfret** [comment]
Closing as the issue seems to be inactive.  Please reopen if its still an issue.
