### ISSUE TITLE
Problem after react-native upgrade

### ISSUE THREAD

**Issue by sambwest** [couchbaselabs/react-native-couchbase-lite#62]
Hi,

I just upgraded to react-native 0.27.2 and I'm getting an error in my system related to this module. 

Error = "Cannot read property 'init' of undefined.

in relation to this line:

```
    ReactCBLite.init(this._localPort, this._localUser, this._localPass, (e) => {
      console.log('DB listening');
    });
```

I have it included as so:

```
import {manager, ReactCBLite} from 'react-native-couchbase-lite'
```

Has anyone else upgraded with success?

**Comment by npomfret** [comment]
I'm using 0.27.2 and its working fine for me.  Do you have any other information? Are there any other errors?  What OS are you using?

**Comment by sambwest** [comment]
Hi,
Sorry, I overwrote some of the installation in the upgrade, my bad, that's why I closed the issue. 

Sam

**Comment by npomfret** [comment]
Great. 

That's a common problem.  Upgrading seems to be quite error prone.
