### ISSUE TITLE
Android Movie example fails with "method PUT must have a request body"

### ISSUE THREAD

**Issue by ssomnoremac** [couchbaselabs/react-native-couchbase-lite#7]
method PUT must have a request body

method
Request.java:244
sendRequest
NetworkingModule.java:128
...
is all I'm getting running ubuntu genymotion emulator (4.4 and 5.1)  of the example movie app for Android great work otherwise!

**Comment by jamesnocentini** [comment]
I think I got this error once. Do you get it consistently? Thanks for opening this ticket

**Comment by ssomnoremac** [comment]
Let me give it another look. I was able to get around it by putting an else
statement in the makeRequest function to return a default body but then I
got an empty listView so the problem is somewhere else. The Movie data in
the sync gateway-- it's there, but when does it get synced to the device
initially? Perhaps that's not happening.

**Comment by ssomnoremac** [comment]
Nested promises in the [index.android/iOS.js files](https://github.com/fraserxu/react-native-couchbase-lite/blob/master/ReactNativeCouchbaseLiteExample/index.android.js#L45) are an [anti-pattern](http://taoofcode.net/promise-anti-patterns/) and I that inner `then()` call wasn't firing for me anyway so I rearranged it. Can we use `all()` here instead? That still didn't fix the inital PUT error though and I actually had to restrict the 'else' fix I mentioned to only apply to PUTs so a couple of things here to look at.
Has anyone else tested on Android? I have it working but would like to know which, if any of these, is perhaps only an Android problem.

**Comment by ssomnoremac** [comment]
for the demo (not the original issue), `all` is not necessary but shouldn't the promise chain be:
1. replicate
2. getAllDocuments
3. setState
like [this](https://github.com/ssomnoremac/react-native-couchbase-lite/commit/c381a1c076d9993e60a68962b745e3dd85fd2fbb)

**Comment by jamesnocentini** [comment]
Yes definitely! Merged your pull request. I ran the example in Genymotion 5.1.0 but couldn't see the issue. Might be a good idea to take a screenshot of the red screen if you see it again and copy it here for future reference.

**Comment by ssomnoremac** [comment]
Sure, actually I've found the issue with the same red screen. It's a problem with [react-native using okhttp](https://github.com/facebook/react-native/issues/3371) 

Seems it was patched but we are currently still using RN=0.14. Suggest we update to 0.17. I can submit another PR but @jamiltz if you are able to test both platforms it might make sense for you to try it. Don't know why it's not replicated on your end but I think, considering the development stage or RN Android we are best off keeping up with the latest.

**Comment by ghost** [comment]
I got the same error too on Android.

**Comment by jamesnocentini** [comment]
Oh so the workaround is to send a request with an empty body? That issue would likely happen when creating the database with POST `:5984/{db-name}`.

**Comment by ssomnoremac** [comment]
yeah, in later versions of the RN implementation of okhttp I think this was [fixed](https://github.com/facebook/react-native/issues/3371) but yeah, my workaround and theirs was to return an empty string. I've been adding to this package quite a bit. I'll try to open a PR or some other issues soon.

**Comment by jamesnocentini** [comment]
Great thanks!

**Comment by jamesnocentini** [comment]
Closing this for now.
