### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by sambwest** [couchbaselabs/react-native-couchbase-lite#70]
Hi,

Is it possible to count values grouped by date?

Are there any plans to expose the Native Query object to react native? The couchbase lite REST interface seems very limited. 

Thanks

**Comment by sambwest** [comment]
After allot of stumbling around I have found some documentation that is usable. It seems that the CBL rest interface can do allot more than the documentation here or in the CBL rest documentation.

There are allot more parameters that appear to work:
http://docs.couchdb.org/en/latest/api/ddoc/views.html#db-design-design-doc-view-view-name

The views also support reduce and show functions:
http://docs.couchdb.org/en/latest/couchapp/ddocs.html#viewfun

I almost walked away from this project but I'm glad I persevered! What is your preferred method for updating the documentation? Are you happy for me to make some updates and submit a pull request as I did before or would you prefer I left you to it?

**Comment by adamski** [comment]
Yes it seems since CouchbaseLite is basically couchdb, those docs are also useful... agree it would be good to have all relevant parts over here too.

**Comment by jamesnocentini** [comment]
We're in the process of migrating to swagger to document the rest apis (most endpoints are the same as CouchDB but not all of them). The work in progress is at http://docs.couchbasemobile.com/couchbase-lite/ and instructions to contribute to the spec are at https://github.com/couchbaselabs/couchbase-mobile-portal/tree/master/swagger.

The neat thing about swagger is that it can dynamically generate a js wrapper (https://github.com/couchbaselabs/react-native-couchbase-lite#swaggerjs-wip), hence it's always up to date with the docs. This is still very much a work in progress but I wanted to shed some light on where we're going with the docs.

The best way to contribute going forward is to open PRs on the swagger spec in the couchbase-mobile-portal repo. Let me know if you have any questions. Thanks!

**Comment by sambwest** [comment]
That documentation still doesn't even touch on the design document or how to use grouping,  reduce etc. As @adamski said, the couchdb docs are relevant. Are they also going to be in the swagger system? 

As a new user to couchdb it is very confusing what is possible and what isn't. In my opinion, if there are couchdb docs which are relevant at the least they should be linked to and explained how the two products link together.
