### ISSUE TITLE
How to do filtered replication?

### ISSUE THREAD

**Issue by kevinblade** [couchbaselabs/react-native-couchbase-lite#73]
Hi!

The replicate method in this module may not support filtered replication.
That only support full replication, right?
I have tried to do it with makeRequest. But it also can't do that.
How can I resolve this issue?
Thanks advance.

**Comment by jamesnocentini** [comment]
This is the limitation of having a custom JS wrapper. The SwaggerJS lib will give us those options https://github.com/couchbaselabs/react-native-couchbase-lite#swaggerjs-wip. Are you looking to do filtered pull or push, with which server?

**Comment by jamesnocentini** [comment]
For filtered pull replications with Sync Gateway, the request body would look like:

```
{
"query_params": {
"channels": "nyc,london"
},
"filter": "sync_gateway/bychannel",
"source": {
"url": "http://localhost:4984/sg-test/"
},
"target": {
"url": "cblite-test"
}
}
```

This triggers a pull replication from `sg-test` to `cblite-test` for docs in the nyc and london channels only.

**Comment by kevinblade** [comment]
Thanks to your comments.
I have used to couchdb server.
I read which couchdb is compatible with couchbase sync protocol from somewhere articles.
So, I am using couchdb and couchbase lite for my current project.
Do you have another comments or recommends for me?

**Comment by kevinblade** [comment]
Yes. I am looking to do filtered pull or push with between couchdb and couchbase lite on mobile.
Follow is my params for makeRequest.
database.makeRequest("POST", "http://admin:password@localhost:5984/team", {}, {
      source: { url: "http://localhost:6984/team" },
      target: { url: "team" },
      filter: "main/teams",
      continuous: true
    });

In developing environment, I am using couchdb with port 6984 on Mac and ReactCBLite.init(5984, 'admin', 'password') is on simulator.
How about that?

**Comment by jamesnocentini** [comment]
Yes that looks good, I've just checked with swagger js and it works too https://github.com/couchbaselabs/react-native-couchbase-lite/blob/master/ReactNativeCouchbaseLiteExample/index.ios.js#L60-L76.
