### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by henchan** [couchbaselabs/react-native-couchbase-lite#79]
Following the instructions below:

```
npm install --save react-native-couchbase-lite
```

gives error

```
npm ERR! fetch failed https://registry.npmjs.org/rnpm/-/rnpm-1.6.5.tgz
```

Seen this error under both OS/X and Ubuntu (Docker client). Using latest versions of npm (2.1.5) and node (4.4.7).
react-native-cli: 1.0.0
react-native: 0.30.0

After manually installing rnpm globally and trying

```
rnpm link react-native-couchbase-lite 
```

getting error 

```
rnpm-link ERR! It seems something went wrong while linking. Error: spawn EACCES 
```

**Comment by npomfret** [comment]
This happened to me recently.  I think I just installed it manually in the end.  I don't think CBL works with rnpm at the moment

**Comment by jamesnocentini** [comment]
Oh, there is an issue with rnpm-postlink.js. If you run the following it should work:

```
chmod +x node_modules/react-native-couchbase-lite/scripts/rnpm-postlink.js
```

I've updated the readme because I don't how to fix the issue yet (if a change in permission is kept after running npm install...).

**Comment by jamesnocentini** [comment]
Oh turns out marking the file as executable and checking it in seems to work. Updated on npm to 0.5.2. It works on my machine so far. Hopefully it works for everyone now.
