### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeCouchbaseLite.ReactCBLite.init')

### ISSUE THREAD

**Issue by hhashmi** [couchbaselabs/react-native-couchbase-lite#80]
import {manager, ReactCBLite} from 'react-native-couchbase-lite'
const dbName = 'dbABC'
const database = new manager(`http://admin:pass@localhost:5984/`, dbName)

new Promise((resolve, reject) => {
  ReactCBLite.init(5984, 'admin', 'pass', error => {
    error ? reject(error) : resolve()
  })
}).then(() => {
  return database.createDatabase()
})
## export default database

W/ReactNativeJS( 2780): Possible Unhandled Promise Rejection (id: 0):
W/ReactNativeJS( 2780): undefined is not an object (evaluating '_reactNativeCouchbaseLite.ReactCBLite.init')
W/ReactNativeJS( 2780): http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:79701:38
W/ReactNativeJS( 2780): tryCallTwo@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:29600:3
W/ReactNativeJS( 2780): doResolve@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:29755:19
W/ReactNativeJS( 2780): Promise@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:29621:10
W/ReactNativeJS( 2780): http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:79700:12
W/ReactNativeJS( 2780): loadModuleImplementation@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:127:8
W/ReactNativeJS( 2780): guardedLoadModule@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:70:32
W/ReactNativeJS( 2780): _require@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:54:18
W/ReactNativeJS( 2780): http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:1504:21
W/ReactNativeJS( 2780): loadModuleImplementation@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:127:8
W/ReactNativeJS( 2780): guardedLoadModule@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:63:37
W/ReactNativeJS( 2780): _require@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:54:18
W/ReactNativeJS( 2780): global code@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:80638:9

**Comment by npomfret** [comment]
You need to create the manager in the call back using the url it provides:

```
import {manager, ReactCBLite} from 'react-native-couchbase-lite'

ReactCBLite.init((url) => {
      // instantiate a new database
      var database = new manager(url, 'my app')
      database.createDatabase()
        .then(() => database.getAllDocuments())
        .then(res => {
          this.setState({
            dataSource: this.state.dataSource.cloneWithRows(res.rows)
          });
        });
    });
```

**Comment by hhashmi** [comment]
import {manager, ReactCBLite} from 'react-native-couchbase-lite';
const url = `http://admin:pass@localhost:5984/`;
const dbName = 'dbABC';

ReactCBLite.init((url) => {
      // instantiate a new database
      var database = new manager(url, dbName);
      database.createDatabase()
        .then(() => database.getAllDocuments())
        .then(res => {
          this.setState({
            dataSource: this.state.dataSource.cloneWithRows(res.rows)
          });
        });
    });

---

E/ReactNativeJS( 2875): undefined is not an object (evaluating '_reactNativeCouchbaseLite.ReactCBLite.init')
E/ReactNativeJS( 2875): Module AppRegistry is not a registered callable module.

**Comment by npomfret** [comment]
Have you installed it as a native npm module?

`rnpm link react-native-couchabse-lite`

**Comment by hhashmi** [comment]
Yes I did and following was its out put

rnpm-link info Linking react-native-couchbase-lite android dependency
rnpm-link info Android module react-native-couchbase-lite has been successfully linked
rnpm-link info Linking react-native-couchbase-lite ios dependency
rnpm-link info iOS module react-native-couchbase-lite has been successfully linked
rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/rnpm/rnpm/issues

at some discussion forum I got to know that it is due to iOS as I'm on windows platform, but still for android it is done.

**Comment by npomfret** [comment]
Sounds like thats the problem. Does your MainApplication.java contain this line `new ReactCBLiteManager()` ?

**Comment by hhashmi** [comment]
my MainApplication.java only contains 

import me.fraserxu.rncouchbaselite.ReactCBLiteManager;

**Comment by npomfret** [comment]
Thats the problem, its not linked correctly.  You can do it manually.  Maybe look at the [example](https://github.com/couchbaselabs/react-native-couchbase-lite/blob/master/ReactNativeCouchbaseLiteExample/android/app/src/main/java/com/reactnativecouchbaseliteexample/MainActivity.java)

**Comment by hhashmi** [comment]
If I simply copy paste the whole file should it work ?

**Comment by hhashmi** [comment]
Now my file looks like this

```

> package com.myTestApp;
> 
> import com.facebook.react.ReactActivity;
> import me.fraserxu.rncouchbaselite.ReactCBLiteManager;
> 
> public class MainActivity extends ReactActivity {
> 
>     /**
>      * Returns the name of the main component registered from JavaScript.
>      * This is used to schedule rendering of the component.
>      */
>     @Override
>     protected String getMainComponentName() {
>         return "myTestApp";
>     }
>   
>    @Override
>     protected boolean getUseDeveloperSupport() {
>         return BuildConfig.DEBUG;
>     }
> 
>     /**
>      * A list of packages used by the app. If the app uses additional views
>      * or modules besides the default ones, add more packages here.
>      */
>     @Override
>     protected List<ReactPackage> getPackages() {
>         return Arrays.<ReactPackage>asList(
>             new MainReactPackage(),
>             new ReactCBLiteManager()
>         );
>     }
> }

```

and on execution I get following error msg

E/ReactNativeJS( 9526): Missing Realm constructor - please ensure RealmReact framework is included!
E/ReactNativeJS( 9526): Module AppRegistry is not a registered callable module.

**Comment by hhashmi** [comment]
I;m trying to do it manually as described at (only for android)
https://github.com/couchbaselabs/react-native-couchbase-lite 

2nd point it says 
Add the Couchbase Maven repository to android/build.gradle

> // add couchbase url
>                 maven {
>                         url "http://files.couchbase.com/maven2/"
>                 }

my current file has following lines

>  maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/../node_modules/react-native/android"
>         }

my question is do I have to replace current url with couchbase url or something else. 
Please guide.

**Comment by npomfret** [comment]
Add a new one (check the example project!) https://github.com/couchbaselabs/react-native-couchbase-lite/blob/master/ReactNativeCouchbaseLiteExample/android/build.gradle

**Comment by hhashmi** [comment]
every thing done according to instructions provided at 
https://github.com/couchbaselabs/react-native-couchbase-lite

no build errors but when application launched in android simulator following error appears

> E/ReactNativeJS(17014): undefined is not an object (evaluating '_reactNativeCouchbaseLite.ReactCBLite.init')
> E/ReactNativeJS(17014): Module AppRegistry is not a registered callable module.

how I'm doing it,
I have a db.js

> import {manager, ReactCBLite} from 'react-native-couchbase-lite';
> 
> const url = `http://admin:pass@localhost:5984/`;
> const dbName = 'dbABC';
> 
> ReactCBLite.init((url) => {
>       // instantiate a new database
>       var database = new manager(url, dbName);
>       database.createDatabase()
>         .then(() => database.getAllDocuments())
>         .then(res => {
>           this.setState({
>             dataSource: this.state.dataSource.cloneWithRows(res.rows)
>           });
>         });
>     });
> export default database;

in my index.android.js I'm using 

> var database = require('./js/db');

**Comment by hhashmi** [comment]
W/ReactNativeJS(17014): Possible Unhandled Promise Rejection (id: 0):
W/ReactNativeJS(17014): http error for PUT 'http://local_user:password@localhost:5984/dbname', caused by => TypeError: Network request failed

**Comment by npomfret** [comment]
But you said you didn't have the line `new ReactCBLiteManager()` in your java code?  That's in the instructions, and in the example project.  Its non-optional.  Is your code checked into github - can you share it?

**Comment by hhashmi** [comment]
I created another fresh application and  followed manual setup instructions.
following is my MainActivity.jana

> package com.myapplication; 
> 
> import com.facebook.react.ReactActivity;
> import com.facebook.react.ReactPackage;
> import com.facebook.react.shell.MainReactPackage;
> 
> import java.util.Arrays;
> import java.util.List;
> 
> import me.fraserxu.rncouchbaselite.ReactCBLiteManager;
> 
> public class MainActivity extends ReactActivity {
> 
> ```
> /**
>  * Returns the name of the main component registered from JavaScript.
>  * This is used to schedule rendering of the component.
>  */
> @Override
> protected String getMainComponentName() {
>     return "MyApplication";
> }
> 
> /**
>  * Returns whether dev mode should be enabled.
>  * This enables e.g. the dev menu.
>  */
> @Override
> protected boolean getUseDeveloperSupport() {
>     return BuildConfig.DEBUG;
> }
> 
> /**
>  * A list of packages used by the app. If the app uses additional views
>  * or modules besides the default ones, add more packages here.
>  */
> 
> protected List<ReactPackage> getPackages() {
>     return Arrays.<ReactPackage>asList(
>         new MainReactPackage(),
>         new ReactCBLiteManager()
>     );
> }
> ```
> 
> }

**Comment by dvas0004** [comment]
I've had similar issues, and figured I must be doing something wrong. So I tried to simply clone the example project, ran "npm install" in the project, and tried to run it. However, it threw back a fatal error of some failed dependencies regarding "Module 8". Can anyone else replicate this?

Just clone this repo, CD into example project folder, run npm install and react-native run-android. Does this work for you?

**Comment by npomfret** [comment]
Closing as the issue seems to be inactive.  Please reopen if its still an issue.

The example app needs attention but this is covered in other tickets.

**Comment by kevinblade** [comment]
This issue might be not closed. I also have this same issue. How can I clear this?

**Comment by npomfret** [comment]
Is your app 'linked' correctly?
