### ISSUE TITLE
ReactCBLite.init Promise

### ISSUE THREAD

**Issue by Prudwell** [couchbaselabs/react-native-couchbase-lite#83]
After upgrading from npm versions 0.4.0 to 0.5.2 I'm trying to get the new ReactCBLite.init working for an exported dataLayer object that I can use in redux thunk actions. 

The old way, I had a static url with hardcoded username, password and port. In the new one I have to get the generated url from the callback and I am having issues getting that url before the rest of my code tries to execute. 

[This comment](https://github.com/couchbaselabs/react-native-couchbase-lite/issues/53#issuecomment-222526574) from issue 53 led me to try using a promise to get the program to wait for that URL callback before exporting the dataLayer but I can't get it to work

Forgive the weird structure, this all used to be in an ES6 class and my code expects the database to be inside dataLayer.database. I've removed the usage of an es6 class as I wasn't sure if that was part of the problem.

In this code, the console.log in the promise chain successfully logs the database object. The second console.log, prints out 'undefined' and prints it out before the the promise code executes.

The rest of my code fails as it seems to look at dataLayer.database before it is finished being set.

Any idea what I'm doing wrong?

```
import {manager, ReactCBLite} from 'react-native-couchbase-lite'

var dataLayer = {}

new Promise((resolve, reject) => {
    ReactCBLite.init((url) => {
            resolve(url);
    })
}).then((url) => {
    dataLayer.database = new manager(url, 'the_app');
    console.log(dataLayer.database)
})

console.log(dataLayer.database)

export default dataLayer
```

Screenshots

<img width="515" alt="screen shot 2016-08-12 at 4 07 43 pm" src="https://cloud.githubusercontent.com/assets/11758003/17639425/fa64c050-60a6-11e6-8418-4b1b096a85ed.png">

<img width="534" alt="screen shot 2016-08-12 at 4 09 01 pm" src="https://cloud.githubusercontent.com/assets/11758003/17639440/28deebb8-60a7-11e6-88e7-ef48199cadd8.png">

**Comment by npomfret** [comment]
I would consider making the call to ReactCBLite.init one of the first things that happens in your app.  Don't start anything until that callback has returned.  Basically make the callback the trigger to get the rest of the app started.  You can't access the database at all until that callback has completed.

**Comment by Prudwell** [comment]
Thanks for the input! I'm having more difficulty than I'd like to admit in implementing what you suggested. I've been trying to get it initialized in index.ios.js but react doesn't like me wrapping the base app class or AppRegistry.registerComponent with a function and I'm not quite sure how to get the callback before running the rest of the code without doing that.

If I can get it initialized here in index.ios.js I can pass it down as a prop for components to then pass to redux thunk actions. 

I see in the example for the package it's initialized and used in componentWillMount but I don't know how I'd use it in the rest of my app by using that method. 

Anyone have a quick example of how one might get the callback from ReactCBLite.init before running the rest of the code in this index.ios.js. Thanks and sorry if this is overly basic stuff

```
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import Root           from './app/native/containers/Root';
import configureStore from './app/store/configureStore.webProd.js';
import {manager, ReactCBLite} from 'react-native-couchbase-lite'

const store = configureStore();

class app_main extends Component {
  render() {
    return (
      <Root store={store} />
    );
  }
}

AppRegistry.registerComponent('app_main', () => app_main);

```

**Comment by yonahforst** [comment]
@Prudwell you can still specify the username+password by using the new `initWithAuth` method and continue starting the manager with a hardcoded url.

Just keep in mind, the port number on the returned url can be different if there's already a listener running.

``` js
class CBLite {
  constructor() {
    let url = 'http://admin:pass@localhost:5984/'
    this.database = new manager(url, dbName)    
  }

  initialize() {
    return new Promise((resolve, reject) => {
      ReactCBLite.initWithAuth('admin', 'pass', url => {
        resolve(url)
      })
    }).then(url => {
      return this.database.createDatabase()
    }).then(res => {
      if(res.status == 201) {
        console.log('created database!', res)
      }
    })
 }
}

```

In general, if you want to pause your app while something loads, you can try something like this. (I'm using to load a cached state from AsyncStorage):

``` js
import { Provider } from 'react-redux'
import App from './containers/App'
import createStore from './lib/createStore'

export default class Root extends Component {
    state = {}

    async componentWillMount() {
        let store = await createStore()
        this.setState({store: store})
    }

    render() {
        if (!this.state.store)
            return <View/>

        return (
            <Provider store={this.state.store}>
                <App />
            </Provider>
        )
    }
}
```

**Comment by Prudwell** [comment]
@yonahforst Awesome! This has me on the right track, thanks!

I've been trying these two methods out this morning. I did try initWithAuth out when I first upgraded to the new ReactCBLite.init style a few days ago but the problem you mentioned with port numbers stumped me. Each time I'd reload in the simulator it would autoincrement the port, so the hard coded url solution wasn't working. Apparently the old listeners were still active or at least reserving the port. I've been trying the ReactCBLit.stopListener method that I see in ios/ReactCBLite.m to try to free up ports before calling ReactCBLit.init but no dice. I also tried a method where it checks on that port with manager.getInfo() and only doing ReactCBLite.init if there was no db_name found in the response but it seems those ports stay reserved even if there's no active couchbase lite instance running on it.

**What's the proper way of dealing with port conflicts using hardcoded url? Is there a close/destroy listener method?**

The second method you mentioned is a lifesaver. I tried so many ways to simulate synchronous/blocking loading but couldn't get it working. It looks like I might be able to use that method if I can't get the port conflicts worked out.

Cheers

**Comment by yonahforst** [comment]
@Prudwell - In my app, I was ignoring the port conflicts 😅. There was a listener running on 5984, and I didn't care if it was the one I just instantiated or not; my app would still be able to communicate with the database. But you're 100% right, there should be a way of dealing with them. 

I just tried something real quick and it seems to work. Conitinuing my previous code snippet, here's the `createStore()` function:

``` js
export default async function() {
  await CBLite.initialize()

  const cbLiteMiddleware = createCBLiteMiddleware({
    database: CBLite.database,
    onUpdate: docs => store.dispatch(entitiesChanged(docs))
  })
  //...
```

and then my updated `CBLite` class:

``` js
class CBLite {
  async initialize() {
    return await new Promise((resolve, reject) => {
      ReactCBLite.init(url => {
        resolve(url)
      })
    }).then(url => {
      this.database = new manager(url, dbName)    
      return this.database.createDatabase()
    }).then(res => {
      if(res.status == 201) {
        console.log('created database!', res)
      }
    }).then(() => {
      return this.database
    })
  }
```

**Comment by npomfret** [comment]
My suggestion would be to call `ReactCBLite.init` at the start of your app: 

```
componentDidMount() {
  const self = this;

  ReactCBLite.init(url => {
    const manager = new manager(url, dbName);

    // the rest of you app's initialisation code goes here
    // just pass the manager into whatever objects need access to it

    const myDbStuff = new DbStuff(manager);

    self._myDbStuff = myDbStuff;
    //or maybe
    self.setState({myDbStuff: myDbStuff});
  })
}

```

**Comment by Prudwell** [comment]
Success! I do indeed init in a componentDidMount now and am using @yonahforst 's tip about loading a blank view in the main render until the database is set . I'm passing the database manager object down in props which feels kind of weird but at least my redux thunk actions are more functional in style now. 

My replicate function arguments also needed to be tweaked as that seems to have changed from the version I was using but it's all working now.

Thanks for the help on this!

**Comment by Prudwell** [comment]
Side question: How often do the NPM versions get updated? The whole reason I started this upgrade process was due to the problem of the cblite listener dropping when the app gets backgrounded or the phone locked. Right now I've manually copied the current master of this project into my node_modules folder as the NPM latest doesn't have the fix for that issue yet. 

Also I'm wondering if maybe the docs could use a little more focus on the internalUrl way of doing things as it seems like the dropped listener issue makes the older way basically un-usable for a real app on iOS. Only after diving into the Issues did I learn about this stuff. 

Loving this project though. Makes me giddy to update something on my phone in Airplane mode, then turn wifi back on and see the change populate through sync gateway to the simulator instance of the app on my laptop. Thanks for all the hard work you guys have put in, it's really nice having this binding for react native!

**Comment by npomfret** [comment]
@jamiltz is the one who up's the NPM version.  

You are right about the docs, and the sample project - they both need some attention.

**Comment by jamesnocentini** [comment]
I've just bumped the version to 0.5.3.

As for the documentation of the current endpoints, we're aiming to have one library based on the documentation that will be used for web apps/phonegap/react native.. Here's a preliminary guide that explains how to set it up in a phonegap app https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/md-docs/ready/guides/rest-apis/swagger-client.md (it's very similar for react native). And the sample app will be based on this Swagger client so the API on this plugin will change a lot but will be self documented as a result. This is still early days but wanted to share what's coming over the next few weeks.

**Comment by Prudwell** [comment]
Very cool @jamiltz !. I've very much been wanting a single way of doing things for both react native and web. Last time I looked, it was looking like I'd be using some weird calls to {db}/_changes to get pseudo-views from sync gateway to my web interface. I also now see that sync gateway 1.3 has queries! Time to go upgrade. Things move so fast! 

I'm a little unsure of how to proceed now though. Is react-native-couchbase-lite going to deprecated in the future in favor of a swagger based library? Or just altered to work with the swagger stuff? As for web, I assume I should start trying to use the swagger setup as detailed in your link?

Thanks

**Comment by jamesnocentini** [comment]
> I also now see that sync gateway 1.3 has queries!

Yes but you'll have to set a flag in the config file. See http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/sync-gateway/views/index.html. That should be mentioned in the description of the endpoint though! Filed https://github.com/couchbaselabs/couchbase-mobile-portal/issues/445.

> Is react-native-couchbase-lite going to deprecated in the future in favor of a swagger based library? Or just altered to work with the swagger stuff?

It will be altered to use the Swagger JS library api and we'll deprecate the api in https://github.com/couchbaselabs/react-native-couchbase-lite/blob/master/index.js. Both libraries are promise based so although it changes the whole api, the code flow should be quite similar. I plan to push the sample app to this repo next week so that'll be a good time to start looking into react native + swagger :)

> As for web, I assume I should start trying to use the swagger setup as detailed in your link?

Yes, it'd be great to get early feedback on it. For any questions/issues you can file an issue on https://github.com/couchbaselabs/couchbase-mobile-portal where the swagger spec is maintained.

**Comment by jamesnocentini** [comment]
I've been following Dan Abramov's react redux courses on egghead.io and I'm at the point of the action dispatchers. From @Prudwell :

> I'm passing the database manager object down in props which feels kind of weird but at least my redux thunk actions are more functional in style now.

With the the manager instantiated asynchronously (once the url is returned from the `init` method) I'm not sure how to access it in the action creators. I can't have the manager in a require statement because of the asynchronous loading so passing it in props seems to be the only way so far. But then it means that each action creator will take the manager as a param which seems a bit repetitive. I'm curious to know how you guys have the manager accessible through out the project files.

**Comment by yonahforst** [comment]
I don't store the manager in the state, I have a CBLite class that holds a reference to it. Then I use redux middleware to read changes from the state and send them to the database

[createStore.js](https://gist.github.com/yonahforst/621c2a69dfe0956bb61f13566d593479)
[CBLiteMiddleware.js](https://gist.github.com/yonahforst/3d123600a0c766fa9876a4fa386431bd)
[CBLite.js](https://gist.github.com/yonahforst/072f546d9efa08e2ec7ad18d86f53147)

**Comment by Prudwell** [comment]
My code currently passes the database around as a prop which is indeed very repetitive and feels...messy. 

The previous way that I had it set up in an older version of this package was by including and instantiating a simple database class in actions.js and setting it to a var to be used in the actions below. This worked with the hardcoded url back in the older version and it actually STILL works in my code now that we can use the internal url. 

```
//dataLayer.js

import {manager, ReactCBLite} from 'react-native-couchbase-lite'

ReactCBLite.init( res => {
    console.log('initialized cblite');
});

export default class dataLayer{
    constructor(){
        this.database = new manager("http://lite.couchbase./", 'consumer_app');
    }
}

```

Then in actions

```
//actions .js 
...
import DataLayer from '../native/dataLayer';
export var dataLayer = new DataLayer();
//some call to dataLayer.database
```

I'm not sure I want to rely on that method though because I think it may just be luck that the database listener becomes available before the first call to http://lite.couchbase./ is made elsewhere in my code. It's also unclear to me if ReactCBLite.init is getting called each time I import a single action from actions.js into a component container and whether that means it's creating new (non-internalUrl) listeners each time.

@yonahforst 's way of doing things looks interesting, I'm going to take a look at that. Please if you find any other clean ways of doing it let us know, I'm not very satisfied with how I'm doing it currently.

**Comment by martypenner** [comment]
I'm following the approach of exporting both the manager object and a hot observable that completes when the ReactCBLite callback is called:

``` js
export let userDb;

export const userDbReady$ = Rx.Observable.create(observer => {
  ReactCBLite.init(url => {
    userDb = new Manager(url, 'user_data');
    observer.complete();
  });
}).publishReplay();
userDbReady$.connect();
```

Elsewhere, I'm waiting for that observable to complete before letting the store dispatch actions:

``` js
import * as db from './database';

let shouldBufferActions = true;

db.userDbReady$
  .subscribe(
    null,
    e => console.log('there was an error waiting for databases to initialize', e),
    () => {
      shouldBufferActions = false;
      pendingActions.forEach(action => store.dispatch(action));
    }
  );
```

I think a very similar approach is possible with Promises.
