### ISSUE TITLE
Simple straightforward example

### ISSUE THREAD

**Issue by adamski** [couchbaselabs/react-native-couchbase-lite#85]
I'm trying to update my code to the newer API, and there doesn't seem to be a clear example of: setting up the manager, creating the db if needed, replicating from a remote db, getting some data. 

The examples are over complicated and different for iOS and Android, and don't seem to reflect the new API.

**Comment by npomfret** [comment]
Agreed, the examples need a bit of attention.  I'll try and clean them up if I get time this week.

**Comment by jmn8718** [comment]
I created an app based on the example
https://github.com/jmn8718/RNCouchbaseExample

**Comment by jmn8718** [comment]
I created an app based on the example
https://github.com/jmn8718/RNCouchbaseExample

**Comment by jamesnocentini** [comment]
In the upcoming version, we will use the Swagger spec. The http client has the `help` method which is very convenient for exploring the API while developing. (see the README on the master branch)
