### ISSUE TITLE
Please update README to clarify status

### ISSUE THREAD

**Issue by snej** [couchbaselabs/react-native-couchbase-lite#95]
Please make it clear at the top of the README that this is not an official supported Couchbase product. Some people are using it and then [complaining on the forums](https://forums.couchbase.com/t/current-working-example-of-peer-to-peer-replication/10526) when it doesn't support every use case.

It would also be good to give a rough idea of its development status, like 'alpha' or 'beta' or whatever. Is it considered ready for anyone to use for real shipping apps, or are there things that need to be done before it's stable enough?

**Comment by npomfret** [comment]
Will do.

**Comment by jamesnocentini** [comment]
👍

**Comment by snej** [comment]
Thanks!
