### ISSUE TITLE
Full Text Search

### ISSUE THREAD

**Issue by sambwest** [couchbaselabs/react-native-couchbase-lite#96]
Hi, 

Can anyone point me to any documentation on how todo a simple search. 

e.g. The values is 'I love apple juice', I want to be able to search by 'apple'. It must be possible, any ideas?

Thanks

**Comment by npomfret** [comment]
couchbase lite isn't really a search engine.   you could do something along the line of splitting the text in your field into words and then index each document by the words in it... but i think you'd be disappointed with the results.  A proper text search engine (like lucene) will do clever things like word stemming and understands different languages.  A search for 'apple' would match both 'apples' and 'apple' in english for example.

I'd look around for a native or javascript mobile text search engine if i were you.

**Comment by sambwest** [comment]
Thanks for your response.

For us that kind of rules couchbase lite out as a viable database for a mobile app. There aren't many apps that I can think of that don't need to search in some form or another.

**Comment by npomfret** [comment]
Sure. Databases and search engines are two very different things.  If you're looking for a text search engine then I'd look for that specifically (rather than a database that also has a search engine).  CBL is very much a database.
