### ISSUE TITLE
I can't get this working

### ISSUE THREAD

**Issue by fbeenaerts** [couchbaselabs/react-native-couchbase-lite#97]
I've no development experience in Xcode and very little in react-native. I cloned the GIT repository.
I completed steps under Using rnpm

Some questions:
1) iOS screen: Drag & Drop is into ReactNativeCouchbaseLiteExample X-code project, right? Not in UntitledApp? If I do this, even then I cannot compile the LiteExample. It cannot find the RCTURLRequestHandler.h file.

2) I don't have to do the Install Manually part of the instructions right? It's or RNPM or Install Manually, no?

I get Linker Errors when compiling the UntitledApp: CouchbaseLiteListener/CBLListener.h file not found.

The instructions are not clear enough for me. Can you help me out please?
Thanks

**Comment by djpongh** [comment]
Please direct your comments to the forums. There should be lots of people there that can help you out.
